Added try and catch to not break the app when it is problem with an url
jgamblin/badactors pull request #5
Opened 2017-11-24 17:43 UTC by hugo-glez

when some url do not respond the program breaks. With the try and catch it continues with the next url transparently, no other info is presented.

2018-07-13 17:26 UTC, 4383 requested changes

2018-07-13 17:26 UTC, 4383 commented on badactors.py
> +            pass
Hi @hugo-glez!
This instruction is useless... the `continue` instruction is enough

2018-07-13 17:26 UTC, 4383 commented on reallybadactors.py
> +            pass
this instruction is useless... the `continue` instruction is enough

2018-07-13 17:26 UTC, 4383 commented on twostrikes.py
> +            pass
this instruction is useless... the `continue` instruction is enough

2018-07-13 17:26 UTC, 4383 commented on badactors.py
> +        except:
Here I think you need to manage more properly the exceptions regarding to the raison of the exception raised by `urlopen`.

2018-07-13 17:26 UTC, 4383 commented on reallybadactors.py
> +        except:
Here I think you need to manage more properly the exceptions regarding to the raison of the exception raised by `urlopen`.

2018-07-13 17:26 UTC, 4383 commented on twostrikes.py
> +        except:
Here I think you need to manage more properly the exceptions regarding to the raison of the exception raised by `urlopen`.

2026-03-27 16:54 UTC, jgamblin commented
Hi\! Thank you for this contribution. I'm doing some housekeeping on my GitHub repos and closing PRs that have been open for more than 6 months. This one has been open for quite a while and I don't want to leave it hanging. If the changes are still relevant, please feel free to reopen or submit a fresh PR. Thanks again\!

2026-03-27 16:54 UTC, closed without merging